### ISSUE TITLE
Building error 

### ISSUE THREAD

**Issue by mahdad-es** [Simple-Robotics/proxsuite#289] opened 2023-12-28 07:58 UTC
I am using Visual Studio 17 2022, when i try to build the proxsuite, i get template error , the configeration of project for MSVC is as follows "PS C:\Users\mesmaeil\Documents\proxsuit-m\proxsuite\build> cmake ..
-- Building for: Visual Studio 17 2022
-- Configuring "proxsuite" (http://github.com/Simple-Robotics/proxsuite)
-- Package version (ROS package.xml): 0.6.1
-- The CXX compiler identification is MSVC 19.38.33133.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: C:/cygwin64/bin/pkg-config.exe (found version "2.1.0")
-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- [Proxsuite] Using C++ standard: 17
-- Found Simde: C:/Users/mesmaeil/Downloads/simde-master/simde-master/simde
-- Found Git: C:/Users/mesmaeil/AppData/Local/Programs/Git/cmd/git.exe (found version "2.43.0.windows.1")
-- Found Matio: C:/Users/mesmaeil/Downloads/vcpkg/packages/matio_x64-windows/lib/libmatio.lib
-- Configuring done (2.8s)
-- Generating done (0.3s)
-- Build files have been written to: C:/Users/mesmaeil/Documents/proxsuit-m/proxsuite/build"

"constructible.hpp(52,1): erro
r C3546: '...': there are no parameter packs available to expand [C:\Users\mesmaeil\Documents\proxsuit-m\proxsuite\buil
d\test\proxsuite-test-util.vcxproj]
  (compiling source file '../../test/src/util_f64.cpp')
  C:\Users\mesmaeil\Documents\proxsuit-m\proxsuite\include\proxsuite\linalg\veg\type_traits\constructible.hpp(52,1):
  the template instantiation context (the oldest one first) is
        C:\Users\mesmaeil\Documents\proxsuit-m\proxsuite\include\proxsuite\linalg\veg\type_traits\constructible.hpp(56,
  1):
        see reference to class template instantiation 'proxsuite::linalg::veg::concepts::_veg_detail::test_sfinae_inpla
  ce_constructible<void,T,Ts...>' being compiled"

**Comment by jcarpent** [comment] 2023-12-28 16:48
You can deactivate the build of the test with CMake as follows:
`cmake . -DBUILD_TESTING=OFF`

**Comment by mahdad-es** [comment] 2023-12-29 08:37
> You can deactivate the build of the test with CMake as follows: `cmake . -DBUILD_TESTING=OFF`

Thank you for your response,  i use the proxsuite\include\proxsuite header files in extrernal library of my project ,
during the build of my project i have the similar error in compiling .cpp file with proxsuite header, do you have any suggestion to solve that ,C:\Users\mesmaeil\Documents\nipt-main2\external\proxsuite\linalg\veg\type_traits\constructible.hpp(52,1): error C3546:
'...': there are no parameter packs available to expand [C:\Users\mesmaeil\Documents\nipt-main2\build\nipt.vcxproj]"

> You can deactivate the build of the test with CMake as follows: `cmake . -DBUILD_TESTING=OFF`

**Comment by jcarpent** [comment] 2023-12-29 10:11
Could you provide a reproducible set of commands to execute to test our side?

**Comment by jcarpent** [comment] 2023-12-29 10:12
@jorisv Could you follow this issue?

**Comment by mahdad-es** [comment] 2023-12-29 11:15
> @jorisv Could you follow this issue?
I am using the Proxsuite available header files in my project and put all the header files in proxsuite\include\proxsuite in external folder of my project, but I received an error in the compilation and build of my project, which is like to the case when I want the build the proxsuite in MSVC Without turning off cmake. -DBUILD_TESTING=OFF and by only running cmake. And I think that if I can solve this problem, my project will also be solved.
The steps I do in Windows to build and install proxsuite and I get an error are as follows
1-git clone https://github.com/Simple-Robotics/proxsuite.git --recursive
2-mkdir build & cd build
3-cmake..
cmake ..
-- Configuring "proxsuite" (http://github.com/Simple-Robotics/proxsuite)
-- Package version (ROS package.xml): 0.6.1
-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- [Proxsuite] Using C++ standard: 17
-- Configuring done (0.4s)
-- Generating done (1.6s)
-- Build files have been written to: C:/Users/mesmaeil/Downloads/proxsuite
4-cmake –build .
C:\Users\mesmaeil\Downloads\proxsuite\include\proxsuite\linalg\veg\type_traits\constructible.hpp(52,1): error C3546: '.
..': there are no parameter packs available to expand [C:\Users\mesmaeil\Downloads\proxsuite\test\proxsuite-test-util.v
cxproj]
  (compiling source file 'src/util_f64.cpp')
  C:\Users\mesmaeil\Downloads\proxsuite\include\proxsuite\linalg\veg\type_traits\constructible.hpp(52,1):
  the template instantiation context (the oldest one first) is
        C:\Users\mesmaeil\Downloads\proxsuite\include\proxsuite\linalg\veg\type_traits\constructible.hpp(56,1):
        see reference to class template instantiation 'proxsuite::linalg::veg::concepts::_veg_detail::test_sfinae_inpla
  ce_constructible<void,T,Ts...>' being compiled

C:\Users\mesmaeil\Downloads\proxsuite\include\proxsuite\linalg\veg\type_traits\invocable.hpp(24,1): error C3546: '...':
 there are no parameter packs available to expand [C:\Users\mesmaeil\Downloads\proxsuite\test\proxsuite-test-util.vcxpr
oj]
  (compiling source file 'src/util_f64.cpp')
  C:\Users\mesmaeil\Downloads\proxsuite\include\proxsuite\linalg\veg\type_traits\invocable.hpp(24,1):
  the template instantiation context (the oldest one first) is
        C:\Users\mesmaeil\Downloads\proxsuite\include\proxsuite\linalg\veg\type_traits\invocable.hpp(28,1):
        see reference to class template instantiation 'proxsuite::linalg::veg::concepts::_veg_detail::test_sfinae_fn_on
  ce<void,Fn,Ret,Args...>' being compiled

C:\Users\mesmaeil\Downloads\proxsuite\include\proxsuite\linalg\veg\type_traits\invocable.hpp(28,1): error C3546: '...':
 there are no parameter packs available to expand [C:\Users\mesmaeil\Downloads\proxsuite\test\proxsuite-test-util.vcxpr
oj]
  (compiling source file 'src/util_f64.cpp')

C:\Users\mesmaeil\Downloads\proxsuite\include\proxsuite\linalg\veg\type_traits\invocable.hpp(30,1): error C3546: '...':
 there are no parameter packs available to expand [C:\Users\mesmaeil\Downloads\proxsuite\test\proxsuite-test-util.vcxpr
oj]

**Comment by mahdad-es** [comment] 2024-01-01 16:33
Also In Proxsuite when i try to compile and build with cmake .. -DBUILD_BENCHMARK=ON i get the same template error
mkdir build && cd build
cmake .. -DBUILD_BENCHMARK=ON
cmake --build .
similar to above error
"C:\Users\mesmaeil\Documents\proxsuit-m\proxsuite\include\proxsuite\linalg\veg\type_traits\constructible.hpp(52,1): erro
r C3546: '...': there are no parameter packs available to expand [C:\Users\mesmaeil\Documents\proxsuit-m\proxsuite\buil
d\test\proxsuite-test-util.vcxproj]
  (compiling source file '../../test/src/util_f64.cpp')
  C:\Users\mesmaeil\Documents\proxsuit-m\proxsuite\include\proxsuite\linalg\veg\type_traits\constructible.hpp(52,1):
  the template instantiation context (the oldest one first) is
        C:\Users\mesmaeil\Documents\proxsuit-m\proxsuite\include\proxsuite\linalg\veg\type_traits\constructible.hpp(56,
  1):
        see reference to class template instantiation 'proxsuite::linalg::veg::concepts::_veg_detail::test_sfinae_inpla
  ce_constructible<void,T,Ts...>' being compiled

C:\Users\mesmaeil\Documents\proxsuit-m\proxsuite\include\proxsuite\linalg\veg\type_traits\invocable.hpp(24,1): error C3
546: '...': there are no parameter packs available to expand [C:\Users\mesmaeil\Documents\proxsuit-m\proxsuite\build\te
st\proxsuite-test-util.vcxproj]
  (compiling source file '../../test/src/util_f64.cpp')
 "

**Comment by jorisv** [comment] 2024-01-03 09:33
Hello @mahdad-es,

I'm able to reproduce your issue on Windows. I will try to understand the problem.

**Comment by jorisv** [comment] 2024-01-04 14:59
Hello @mahdad-es,

#290 should fix your problem.
You can checkout the devel branch to try it.

**Comment by mahdad-es** [comment] 2024-01-05 08:25
> Hello @mahdad-es,
> 
> #290 should fix your problem. You can checkout the devel branch to try it.

Hello @jorisv 
Thank you so much for your help , some errors are fixed as you suggested i still have one error,do you have any idea about that?
"C:\Users\mesmaeil\Documents\nipt-main2\external\proxsuite\linalg\veg\tuple.hpp(357,1): error C2059: syntax error: '...'
 [C:\Users\mesmaeil\Documents\nipt-main2\build\nipt.vcxproj]
  (compiling source file '../src/recon_transhi2015.cpp')
  C:\Users\mesmaeil\Documents\nipt-main2\external\proxsuite\linalg\veg\tuple.hpp(357,1):
  the template instantiation context (the oldest one first) is
        C:\Users\mesmaeil\Documents\nipt-main2\external\proxsuite\linalg\veg\tuple.hpp(431,2):
        see reference to class template instantiation 'proxsuite::linalg::veg::tuple::IndexedTuple<proxsuite::linalg::v
  eg::_detail::_meta::integer_sequence<proxsuite::linalg::veg::usize,Is...>*,Ts...>' being compiled"

**Comment by jorisv** [comment] 2024-01-05 10:58
Hello @mahdad-es,

Sorry, I can't reproduce this error.
I have build in Debug and Release with Visual Studio Visual Studio 17 2022 and every thing is fine.

Can you try to build the standalone proxsuite project ? (no the proxsuite header inside your project)

**Comment by mahdad-es** [comment] 2024-01-05 12:05
> Hello @mahdad-es,
> Can you try to build the standalone proxsuite project ? (no the proxsuite header inside your project)
Hello @jorisv
Thank you for your reply, yes, the previous problem was solved and I was able to fix similar errors in my project. The proxsuite project is built completely and only in my project when I use the header files, I encountered this error.

**Comment by jorisv** [comment] 2024-01-07 22:01
Hello @mahdad-es,

It's strange that proxsuite is building as a standalone project but not inside your project.
Can you show me the include order in recon_transhi2015.cpp ?
Also, can you show me the command line used to compile this file ? You can find it by giving the following option to cmake `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`. This will generate the compile_commands.json file in your build directory. You can find the compiler command line inside it.

**Comment by mahdad-es** [comment] 2024-01-08 11:48
Hello @jorisv
thank you for your time
include order in recon_transhi2015.cpp is as follows,when i put the header #include <proxsuite/proxqp/dense/dense.hpp> in my recon_transhi2015.h header file also i give similar error,
"#include "recon_transhi2015.h"
#include "ConstraintSet.h"
#include "../../gradient/dMRI_grad.h"
#include "../../../math/sphere.h"
#include "../../../image/image_operators.h"
#include "../../../surface/surface.h"
#include <optional>
#include <cstdint>
#include <chrono>
#include <iostream>
#include <proxsuite/proxqp/dense/dense.hpp>
#include <proxsuite/proxqp/utils/random_qp_problems.hpp>"
 and command line used to compile this file is as :{
  "directory": "C:/Users/mesmaeil/Documents/nipt-main2/out/build/x64-Debug",
  "command": "C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1438~1.331\\bin\\Hostx64\\x64\\cl.exe  /nologo /TP -DNOMINMAX -D_USE_MATH_DEFINES -IC:\\Users\\mesmaeil\\Documents\\nipt-main2\\src -IC:\\Users\\mesmaeil\\Documents\\nipt-main2\\external -IC:\\Users\\mesmaeil\\Documents\\nipt-main2\\external\\expat -IC:\\Users\\mesmaeil\\Documents\\nipt-main2\\external\\eigen-3.4.0 /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -std:c++17 -MTd   -D BUILD_FOR_WINDOWS /bigobj /wd4244 /wd4267 /wd4996 /wd4305 /wd4101 /FoCMakeFiles\\OBJS.dir\\src\\dMRI\\reconstruction\\transhi2015\\recon_transhi2015.cpp.obj /FdTARGET_COMPILE_PDB /FS -c C:\\Users\\mesmaeil\\Documents\\nipt-main2\\src\\dMRI\\reconstruction\\transhi2015\\recon_transhi2015.cpp",
  "file": "C:\\Users\\mesmaeil\\Documents\\nipt-main2\\src\\dMRI\\reconstruction\\transhi2015\\recon_transhi2015.cpp",
  "output": "CMakeFiles\\OBJS.dir\\src\\dMRI\\reconstruction\\transhi2015\\recon_transhi2015.cpp.obj"
},

**Comment by jorisv** [comment] 2024-01-09 14:40
Hello @mahdad-es,

I tried to use same compile flags than you when building proxsuite but I still can't reproduce the issue.

Can you provide me a minimal CMake project with some code that will allow me to reproduce your issue ?

Thank you

**Comment by mahdad-es** [comment] 2024-01-09 15:56
Thank you for your reply.
I have header files of proxsuite in my external library, is it possible to look my project cmakelists.txt  configuration and following two files of our project.
the error is "
C:\Users\mesmaeil\Documents\nipt-main2\external\proxsuite\linalg\veg\tuple.hpp(357,1): error C2059: syntax error: '...'
 [C:\Users\mesmaeil\Documents\nipt-main2\build\OBJS.vcxproj]
  (compiling source file '../src/dMRI/reconstruction/transhi2015/recon_transhi2015.cpp')
  C:\Users\mesmaeil\Documents\nipt-main2\external\proxsuite\linalg\veg\tuple.hpp(357,1):
  the template instantiation context (the oldest one first) is
        C:\Users\mesmaeil\Documents\nipt-main2\external\proxsuite\linalg\veg\tuple.hpp(431,2):
        see reference to class template instantiation 'proxsuite::linalg::veg::tuple::IndexedTuple<proxsuite::linalg::v
  eg::_detail::_meta::integer_sequence<proxsuite::linalg::veg::usize,Is...>*,Ts...>' being compiled""
[nipt.zip](https://github.com/Simple-Robotics/proxsuite/files/13875961/nipt.zip)

**Comment by mahdad-es** [comment] 2024-01-10 11:28
Hello @jorisv 
Would you please see the following test code. You can reproduce the issue in following test code.
[test.zip](https://github.com/Simple-Robotics/proxsuite/files/13886974/test.zip)

**Comment by mahdad-es** [comment] 2024-01-12 10:40
Hello
could you reproduce the issue in above test code?

**Comment by jorisv** [comment] 2024-01-15 10:01
Hello @mahdad-es,

Thank for the code. I was able to reproduce the issue and I find the error.

You need to give the [/fpermissive-](https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170) compiler option when building proxsuite on Windows .

I strongly recommend you to not embed the proxsuite source in your project. Instead, install it, find the target with find_package and link your project with it. All the defines needed to build are defined in this target, so you wouldn't have had this problem.

**Comment by jcarpent** [comment] 2024-01-16 09:52
I will close this issue as it seems to be solved thanks to the recommendations provided by @jorisv.

**Closed by jcarpent** 2024-01-16 09:52 UTC

**Comment by mahdad-es** [comment] 2024-01-16 11:00
> Hello @jorisv
I really appreciate your recommendations and kind assistance in this regard. My error has been fixed now.
